PsaAdminBundle:
    resource: "@PsaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

PsaUserBundle:
    resource: "@PsaUserBundle/Resources/config/routing.yml"
    prefix:   /

PsaPageBundle:
    resource: "@PsaPageBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile
    
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /admin/register
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /admin/resetting
    
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /admin/change-password